### ISSUE TITLE
Fetch: Client response type

### ISSUE THREAD

**Issue by EgorPopovPP** [orval-labs/orval#1550]
I use 7.0.0 with fetch client and it was amazing
But there is a question
Fetch client return response with data and status fields and it is not what we want
Can i change response type that it return my response type exactly?

Example
Generated code
```
/**
 * @summary Get user blogger info
 */
export type getUserBloggerInfoResponse = {
  data: GetUserBloggerInfoResponse;
  status: number;
};
```

What we need
```
/**
 * @summary Get user blogger info
 */
export type getUserBloggerInfoResponse = GetUserBloggerInfoResponse;
 ```

**Comment by soartec-lab** [comment]
thanks for made issue. Currently it's not supported, but I'll consider it.

**Comment by soartec-lab** [comment]
@EgorPopovPP 
I wanna understand your having problem, so could you tell me your use case ?

**Comment by pbrzosko** [comment]
@EgorPopovPP I had the same issue with this API, as you can see here: https://github.com/orval-labs/orval/discussions/1535. For now I guess the workaround is to use select function (see the discussion link).

@soartec-lab I do not think anyone would need to check the status. Most of the time you just want the data, and if something is not right, then you take the error ref. Maybe you could provide another ref, which would contain response information like status code and text. But I don't think it should be part of the data ref, because there you want to have pure response data properly typed.

**Comment by EgorPopovPP** [comment]
> @pbrzosko
> 
> thank you. Although status is not used, does that mean it won't interfere even if it is present? Or is it complicated to have to write a `select` ?

I not like to write bloggerInfo.data.data. You suggest writing a select every time, which doesn't seem like a good solution to me.

**Comment by soartec-lab** [comment]
Okay, so you want to access the data only through `bloggerInfo.data`, not `bloggerInfo.data.data` right?

**Comment by EgorPopovPP** [comment]
> Okay, so you want to access the data only through `bloggerInfo.data`, not `bloggerInfo.data.data` right?

Yes, it is

**Comment by rob-long** [comment]
> Okay, so you want to access the data only through bloggerInfo.data, not bloggerInfo.data.data right?

@soartec-lab  
Yes, that's my problem as well.  The extra `data` is a pain point.

**Comment by pbrzosko** [comment]
I agree with the above.

**Comment by soartec-lab** [comment]
I see, I understand. This issue is caused by the tanstack query client's dependency on 'orval/fetch'.
`orval/fetch` makes it easier for applications to handle http status, so the response must include the http status.
And since the tanstack query client relies on `orval/fetch`, its response type is inherited.

So i plan to add new configuration properties. That allows `orval` to change the return type to a single type like `Pet` or `Pets`.

**Comment by soartec-lab** [comment]
Hey everyone. I fixed this issue by i added new config option. Please try this 🙌 

https://orval.dev/guides/fetch-client#return-original-defined-return-type
